/* ============================================================
   DATA LAYER — articles, projects, i18n
   ============================================================ */

const I18N = {
  fr: {
    nav_writing: "Journal",
    nav_projects: "Projets",
    nav_about: "À propos",
    nav_search: "Rechercher",
    hero_kicker: "Journal d'un développeur web",
    hero_desc: "J'écris sur le web, les outils que je construis, et les détails qui comptent. Ouvert, curieux, parfois de mauvaise foi.",
    hero_cta: "Lire le dernier article",
    latest: "Derniers articles",
    all_writing: "Tout le journal",
    issue: "Numéro",
    min_read: "min de lecture",
    read: "Lire",
    featured: "À la une",
    projects_title: "Ce que je construis",
    projects_desc: "Paquets, sites et expériences que je fais vivre, parfois la nuit.",
    published: "Publié",
    updated: "Mis à jour",
    tags: "Thèmes",
    filed_under: "Classé dans",
    continue_reading: "Continuer la lecture",
    next_article: "Article suivant",
    prev_article: "Précédent",
    search_ph: "Chercher dans le journal…",
    cmdk_hint: "ouvrir",
    ai_title: "Compagnon de lecture",
    ai_subtitle: "Pose-moi une question sur cet article.",
    ai_placeholder: "Que veux-tu comprendre ?",
    ai_suggest: "Suggestions",
    ai_explain: "Explique ce concept",
    ai_simplify: "Version simple",
    ai_deepen: "Va plus loin",
    ai_thinking: "Je réfléchis…",
    toc: "Sommaire",
    by: "par",
    colophon: "Composé avec Instrument Serif et Newsreader. Écrit en France.",
    back: "Retour",
    est: "Depuis 2021",
    reading_width: "Largeur",
    code_style: "Code",
    theme: "Thème",
    mode_light: "Jour",
    mode_dark: "Nuit",
  },
  en: {
    nav_writing: "Writing",
    nav_projects: "Projects",
    nav_about: "About",
    nav_search: "Search",
    hero_kicker: "A web developer's journal",
    hero_desc: "I write about the web, the tools I build, and the details that matter. Open, curious, occasionally opinionated.",
    hero_cta: "Read latest",
    latest: "Latest writing",
    all_writing: "All writing",
    issue: "Issue",
    min_read: "min read",
    read: "Read",
    featured: "Featured",
    projects_title: "What I'm building",
    projects_desc: "Packages, sites, and experiments I keep alive, often at night.",
    published: "Published",
    updated: "Updated",
    tags: "Topics",
    filed_under: "Filed under",
    continue_reading: "Continue reading",
    next_article: "Next",
    prev_article: "Previous",
    search_ph: "Search the journal…",
    cmdk_hint: "open",
    ai_title: "Reading companion",
    ai_subtitle: "Ask me anything about this article.",
    ai_placeholder: "What do you want to understand?",
    ai_suggest: "Suggestions",
    ai_explain: "Explain this concept",
    ai_simplify: "Simpler version",
    ai_deepen: "Go deeper",
    ai_thinking: "Thinking…",
    toc: "Contents",
    by: "by",
    colophon: "Set in Instrument Serif & Newsreader. Written in France.",
    back: "Back",
    est: "Since 2021",
    reading_width: "Width",
    code_style: "Code",
    theme: "Theme",
    mode_light: "Day",
    mode_dark: "Night",
  }
};

const ARTICLES = [
  {
    id: "shipping-ui-kit",
    slug: "shipping-my-first-npm-package",
    issue: 14,
    date: "2026-04-11",
    readMin: 9,
    tags: { fr: ["npm", "open-source", "outils"], en: ["npm", "open-source", "tooling"] },
    featured: true,
    title: {
      fr: "J'ai publié mon premier package npm — et personne ne s'en fout",
      en: "I shipped my first npm package — and no one should care",
    },
    dek: {
      fr: "Notes honnêtes après trois semaines passées à extraire un bout de code d'un projet pour le donner au reste du monde. Le code n'était pas le problème.",
      en: "Honest notes after three weeks spent extracting a chunk of code from a project to hand it over to the rest of the world. The code wasn't the problem.",
    },
    toc: [
      { id: "premisse", fr: "La prémisse", en: "The premise" },
      { id: "extraction", fr: "L'extraction", en: "The extraction" },
      { id: "api", fr: "Dessiner l'API publique", en: "Designing a public API" },
      { id: "semver", fr: "Semver n'est pas un choix", en: "Semver isn't a choice" },
      { id: "apres", fr: "Après le premier 1.0.0", en: "Life after 1.0.0" },
    ],
    body: "ARTICLE_1",
  },
  {
    id: "portfolio-rewrite",
    slug: "rewriting-my-portfolio-for-the-fifth-time",
    issue: 13,
    date: "2026-03-22",
    readMin: 12,
    tags: { fr: ["portfolio", "design", "personnel"], en: ["portfolio", "design", "personal"] },
    featured: true,
    title: {
      fr: "Réécrire mon portfolio pour la cinquième fois",
      en: "Rewriting my portfolio for the fifth time",
    },
    dek: {
      fr: "Chaque version détruit quelque chose que j'aimais et ajoute une chose que je regretterai. Retour sur edwinfom.dev, cru 2026.",
      en: "Each rewrite kills something I loved and adds something I'll regret. A look back at edwinfom.dev, 2026 edition.",
    },
    toc: [
      { id: "archeologie", fr: "Archéologie personnelle", en: "Personal archaeology" },
      { id: "contraintes", fr: "Contraintes que je me fixe", en: "Self-imposed constraints" },
      { id: "typographie", fr: "La typographie fait le travail", en: "Typography does the heavy lifting" },
      { id: "accessibilite", fr: "Accessibilité n'est pas négociable", en: "Accessibility isn't negotiable" },
    ],
    body: "ARTICLE_2",
  },
  {
    id: "view-transitions",
    slug: "view-transitions-api-one-year-in",
    issue: 12,
    date: "2026-02-18",
    readMin: 7,
    tags: { fr: ["web", "api", "animation"], en: ["web", "api", "animation"] },
    featured: false,
    title: {
      fr: "View Transitions, un an plus tard",
      en: "View Transitions, one year in",
    },
    dek: {
      fr: "J'ai passé l'année à remplacer Framer Motion par trois lignes de CSS. Voici ce qui marche, et ce qui casse encore.",
      en: "I spent a year replacing Framer Motion with three lines of CSS. Here's what holds up, and what still breaks.",
    },
    toc: [
      { id: "idee", fr: "L'idée", en: "The idea" },
      { id: "pratique", fr: "En pratique", en: "In practice" },
      { id: "pieges", fr: "Pièges", en: "Gotchas" },
    ],
    body: "ARTICLE_3",
  },
  {
    id: "monorepo-packages",
    slug: "a-monorepo-for-three-packages",
    issue: 11,
    date: "2026-01-30",
    readMin: 11,
    tags: { fr: ["monorepo", "pnpm", "DX"], en: ["monorepo", "pnpm", "DX"] },
    featured: false,
    title: {
      fr: "Un monorepo pour trois packages",
      en: "A monorepo for three packages",
    },
    dek: {
      fr: "Pourquoi packages.edwinfom.dev est devenu un workspace pnpm + changesets, et ce que j'aurais aimé savoir avant.",
      en: "Why packages.edwinfom.dev became a pnpm + changesets workspace, and what I wish I'd known.",
    },
    toc: [
      { id: "pourquoi", fr: "Pourquoi", en: "Why" },
      { id: "structure", fr: "Structure", en: "Structure" },
      { id: "publication", fr: "Publication automatisée", en: "Automated publishing" },
    ],
    body: "ARTICLE_4",
  },
  {
    id: "contribs-htmx",
    slug: "my-first-real-open-source-contribution",
    issue: 10,
    date: "2025-12-14",
    readMin: 6,
    tags: { fr: ["open-source", "contrib"], en: ["open-source", "contrib"] },
    featured: false,
    title: {
      fr: "Ma première vraie contribution open-source",
      en: "My first real open-source contribution",
    },
    dek: {
      fr: "Une PR de sept lignes. Trois jours de review. Zéro regret.",
      en: "A seven-line PR. Three days of review. Zero regrets.",
    },
    toc: [
      { id: "bug", fr: "Le bug", en: "The bug" },
      { id: "fix", fr: "La correction", en: "The fix" },
      { id: "lecon", fr: "Ce que j'ai appris", en: "What I learned" },
    ],
    body: "ARTICLE_5",
  },
  {
    id: "type-system",
    slug: "a-type-system-for-a-blog",
    issue: 9,
    date: "2025-11-02",
    readMin: 8,
    tags: { fr: ["typographie", "design"], en: ["typography", "design"] },
    featured: false,
    title: {
      fr: "Un système typographique pour un blog",
      en: "A type system for a blog",
    },
    dek: {
      fr: "Trois polices, une échelle modulaire, et la règle que je brise tout le temps.",
      en: "Three typefaces, one modular scale, and the rule I keep breaking.",
    },
    toc: [
      { id: "pairing", fr: "Le pairing", en: "The pairing" },
      { id: "echelle", fr: "L'échelle", en: "The scale" },
      { id: "rythme", fr: "Rythme vertical", en: "Vertical rhythm" },
    ],
    body: "ARTICLE_6",
  },
];

const PROJECTS = [
  {
    id: "portfolio",
    name: "edwinfom.dev",
    year: "2026",
    kind: { fr: "Portfolio", en: "Portfolio" },
    desc: {
      fr: "Cinquième itération. Écrit en Astro, déployé en trois secondes, composé en une nuit.",
      en: "Fifth iteration. Written in Astro, deployed in three seconds, composed in one night.",
    },
    url: "https://www.edwinfom.dev/",
    tags: ["Astro", "Tailwind", "Vercel"],
    status: "live",
  },
  {
    id: "packages",
    name: "packages.edwinfom.dev",
    year: "2026",
    kind: { fr: "Monorepo", en: "Monorepo" },
    desc: {
      fr: "Un hub pour les petits paquets npm que je publie — utilitaires React, hooks, helpers typographiques.",
      en: "A hub for the small npm packages I publish — React utilities, hooks, typography helpers.",
    },
    url: "https://packages.edwinfom.dev/",
    tags: ["pnpm", "changesets", "TypeScript"],
    status: "live",
  },
  {
    id: "journal",
    name: "journal.edwinfom.dev",
    year: "2026",
    kind: { fr: "Blog", en: "Blog" },
    desc: {
      fr: "Ce journal. Écrit en MDX, lu par toi. Compagnon IA contextuel intégré.",
      en: "This journal. Written in MDX, read by you. Built-in contextual AI companion.",
    },
    url: "#",
    tags: ["MDX", "React", "AI"],
    status: "new",
  },
  {
    id: "tinykit",
    name: "@edwinfom/tinykit",
    year: "2025",
    kind: { fr: "Package npm", en: "npm package" },
    desc: {
      fr: "Primitives React sans dépendances : useFocusTrap, usePress, useViewTransition. Moins de 3kb.",
      en: "Zero-dep React primitives: useFocusTrap, usePress, useViewTransition. Under 3kb.",
    },
    url: "#",
    tags: ["React", "TypeScript", "0-dep"],
    status: "live",
  },
  {
    id: "type-scale",
    name: "@edwinfom/type-scale",
    year: "2025",
    kind: { fr: "Package npm", en: "npm package" },
    desc: {
      fr: "Un générateur d'échelles typographiques modulaires, pensé pour CSS et Tailwind.",
      en: "A modular type-scale generator, designed for CSS and Tailwind.",
    },
    url: "#",
    tags: ["Design tokens", "CSS"],
    status: "live",
  },
  {
    id: "writing-machine",
    name: "writing-machine",
    year: "2025",
    kind: { fr: "Expérience", en: "Experiment" },
    desc: {
      fr: "Un éditeur markdown minimaliste qui m'aide à écrire ce journal. Plein écran, sans menu, sans autocomplétion.",
      en: "A minimalist markdown editor that helps me write this journal. Full screen, no menu, no autocomplete.",
    },
    url: "#",
    tags: ["Editor", "Personal"],
    status: "wip",
  },
];

/* ============================================================
   ARTICLE BODIES — shaped as structured blocks
   ============================================================ */
const BODIES = {
  ARTICLE_1: {
    fr: [
      { type: "p", text: "Il y a trois semaines, j'ai publié mon premier package sur npm. Sept kilo-octets, aucun téléchargement, et cette petite fierté qu'on ressent quand on voit son nom dans le registre officiel. J'ai mis plus de temps à choisir le nom qu'à écrire le code." },
      { type: "p", text: "Je voulais extraire un hook React que j'utilisais dans deux projets différents — <code>useViewTransition</code>. Rien d'extraordinaire : une sucrerie autour de l'API native du navigateur, avec une gestion propre des fallback. Mais le geste de le sortir de mon dossier <code>utils</code> m'a obligé à repenser des choses que j'avais ignorées pendant des mois." },
      { type: "h2", id: "premisse", text: { fr: "La prémisse", en: "The premise" } },
      { type: "p", text: "Publier un package, c'est écrire un contrat. Tu promets à une poignée d'inconnus que ton bout de code ne va pas casser leur build samedi à deux heures du matin. C'est une promesse qui n'engage que toi, et qui te suit." },
      { type: "quote", text: "Un package, c'est moins un produit qu'une relation." },
      { type: "h2", id: "extraction", text: { fr: "L'extraction", en: "The extraction" } },
      { type: "p", text: "La première tâche, c'est l'archéologie. Retrouver toutes les variables implicites, toutes les dépendances croisées, tous les petits <code>// TODO</code> qu'on s'était juré de nettoyer. J'ai fini par réécrire 80% du hook." },
      { type: "code", lang: "ts", code: "// Avant : couplé au contexte de mon app\nexport function useViewTransition(router) {\n  const route = router.current;\n  // ...mélange de responsabilités\n}\n\n// Après : une API que tu peux comprendre en 5 secondes\nexport function useViewTransition(\n  callback: () => void | Promise<void>,\n  options?: { skip?: boolean }\n) {\n  if (options?.skip || !document.startViewTransition) {\n    return callback();\n  }\n  return document.startViewTransition(callback);\n}" },
      { type: "h2", id: "api", text: { fr: "Dessiner l'API publique", en: "Designing a public API" } },
      { type: "p", text: "Pendant trois jours, j'ai dessiné l'API sur un carnet avant d'écrire la moindre ligne. Chaque argument optionnel est une dette future. Chaque nom que tu exposes est un nom que tu ne peux plus renommer sans bump majeur." },
      { type: "list", items: [
        "Une fonction, un travail",
        "Les booléens sont des pièges",
        "Les types exportés comptent autant que les valeurs",
        "Un README court vaut mieux qu'un long"
      ]},
      { type: "h2", id: "semver", text: { fr: "Semver n'est pas un choix", en: "Semver isn't a choice" } },
      { type: "p", text: "J'ai voulu faire le malin et publier en <code>0.1.0</code>. Un mainteneur d'un projet que j'admire m'a gentiment rappelé que <code>0.x.y</code> veut dire \"je peux tout casser\", et que personne ne dépend sérieusement d'un zéro-majeur. Un 1.0.0 honnête est toujours mieux qu'un 0.9.9 timide." },
      { type: "h2", id: "apres", text: { fr: "Après le premier 1.0.0", en: "Life after 1.0.0" } },
      { type: "p", text: "Le code est la partie facile. Le vrai travail commence après : répondre aux issues, accepter qu'on ne contrôle plus l'usage, décider quand dire non. Un package publié, c'est un être vivant. Et comme tout être vivant, il a besoin d'attention, ou il meurt." },
      { type: "p", text: "Quelques leçons. La documentation est le produit. Les exemples valent mille props de type. Et si personne ne l'utilise, ce n'est pas grave — tu l'as extrait pour toi d'abord." },
    ],
    en: [
      { type: "p", text: "Three weeks ago, I shipped my first npm package. Seven kilobytes, zero downloads, and that small pride of seeing your name in the official registry. Picking the name took longer than writing the code." },
      { type: "p", text: "I wanted to extract a React hook I was using across two projects — <code>useViewTransition</code>. Nothing extraordinary: a thin wrapper around the browser's native API, with a clean fallback. But the act of pulling it out of my <code>utils</code> folder forced me to reconsider things I'd ignored for months." },
      { type: "h2", id: "premisse", text: { fr: "La prémisse", en: "The premise" } },
      { type: "p", text: "Publishing a package is writing a contract. You promise a handful of strangers that your bit of code won't break their build on Saturday at 2am. It's a promise only you are bound by, and it follows you." },
      { type: "quote", text: "A package is less a product than a relationship." },
      { type: "h2", id: "extraction", text: { fr: "L'extraction", en: "The extraction" } },
      { type: "p", text: "The first task is archaeology. Finding every implicit variable, every cross dependency, every little <code>// TODO</code> you'd sworn to clean up. I ended up rewriting 80% of the hook." },
      { type: "code", lang: "ts", code: "// Before: coupled to my app's context\nexport function useViewTransition(router) {\n  const route = router.current;\n  // ...mixed concerns\n}\n\n// After: an API you can grok in 5 seconds\nexport function useViewTransition(\n  callback: () => void | Promise<void>,\n  options?: { skip?: boolean }\n) {\n  if (options?.skip || !document.startViewTransition) {\n    return callback();\n  }\n  return document.startViewTransition(callback);\n}" },
      { type: "h2", id: "api", text: { fr: "Dessiner l'API publique", en: "Designing a public API" } },
      { type: "p", text: "For three days I sketched the API in a notebook before writing a line. Every optional argument is future debt. Every name you expose is one you can't rename without a major bump." },
      { type: "list", items: [
        "One function, one job",
        "Booleans are traps",
        "Exported types matter as much as values",
        "A short README beats a long one"
      ]},
      { type: "h2", id: "semver", text: { fr: "Semver n'est pas un choix", en: "Semver isn't a choice" } },
      { type: "p", text: "I tried to play it cool and publish as <code>0.1.0</code>. A maintainer I admire gently reminded me that <code>0.x.y</code> means \"I can break everything\" and nobody seriously depends on a zero-major. An honest 1.0.0 beats a timid 0.9.9." },
      { type: "h2", id: "apres", text: { fr: "Après le premier 1.0.0", en: "Life after 1.0.0" } },
      { type: "p", text: "Code is the easy part. Real work begins after: answering issues, accepting you no longer control usage, deciding when to say no. A published package is a living thing. Like any living thing, it needs attention, or it dies." },
      { type: "p", text: "A few lessons. Documentation is the product. Examples beat a thousand prop types. And if no one uses it, that's fine — you extracted it for yourself first." },
    ]
  },
  ARTICLE_2: {
    fr: [
      { type: "p", text: "J'ai réécrit mon portfolio cinq fois en quatre ans. Chaque fois, je me jure que c'est la dernière. Chaque fois, six mois plus tard, je rouvre le dépôt avec ce regard qu'on a pour ses vieilles photos : tendre, mais ferme." },
      { type: "h2", id: "archeologie", text: { fr: "Archéologie personnelle", en: "Personal archaeology" } },
      { type: "p", text: "La première version était un template Next.js. La deuxième un truc avec dix animations Framer Motion qui chargeait en trois secondes. La troisième un Astro minimaliste. La quatrième un WebGL stupidement ambitieux. La cinquième — celle-ci — tient sur une page." },
      { type: "quote", text: "Chaque portfolio est une lettre à toi-même dans six mois." },
      { type: "h2", id: "contraintes", text: { fr: "Contraintes que je me fixe", en: "Self-imposed constraints" } },
      { type: "list", items: [
        "Zéro JavaScript côté client par défaut",
        "Aucune image au-dessus de la ligne de flottaison",
        "Largeur de lecture maximale : 680 pixels",
        "Tout doit tenir en un article moyen"
      ]},
      { type: "h2", id: "typographie", text: { fr: "La typographie fait le travail", en: "Typography does the heavy lifting" } },
      { type: "p", text: "Quand tu retires les couleurs criardes, les animations de chargement, les carrousels de témoignages — il reste la typographie. Et c'est beaucoup. Un bon pairing serif/sans, une échelle modulaire disciplinée, un interligne généreux, et quatre-vingt pour cent du travail est fait." },
      { type: "code", lang: "css", code: "/* L'échelle que j'utilise partout */\n:root {\n  --step--2: clamp(.75rem, .72rem + .13vw, .83rem);\n  --step--1: clamp(.875rem, .83rem + .21vw, 1rem);\n  --step-0:  clamp(1rem, .93rem + .35vw, 1.25rem);\n  --step-1:  clamp(1.25rem, 1.14rem + .57vw, 1.6rem);\n  --step-2:  clamp(1.56rem, 1.38rem + .9vw, 2.1rem);\n  --step-3:  clamp(1.95rem, 1.68rem + 1.4vw, 2.75rem);\n}" },
      { type: "h2", id: "accessibilite", text: { fr: "Accessibilité n'est pas négociable", en: "Accessibility isn't negotiable" } },
      { type: "p", text: "Un portfolio inaccessible raconte une chose sur toi avant que tu n'aies dit un mot. Lighthouse à 100 n'est pas un trophée — c'est un seuil. Ensuite commence le vrai travail : navigation clavier, contrastes, landmarks, <code>prefers-reduced-motion</code>." },
      { type: "p", text: "La sixième version arrivera. Probablement plus tôt que je ne le pense." },
    ],
    en: [
      { type: "p", text: "I've rewritten my portfolio five times in four years. Each time I swear it's the last. Six months later, I reopen the repo with that look you give your old photos: fond, but firm." },
      { type: "h2", id: "archeologie", text: { fr: "Archéologie personnelle", en: "Personal archaeology" } },
      { type: "p", text: "V1 was a Next.js template. V2 had ten Framer Motion animations and loaded in three seconds. V3 was a minimalist Astro. V4 was a stupidly ambitious WebGL. V5 — this one — fits on a single page." },
      { type: "quote", text: "Every portfolio is a letter to yourself six months from now." },
      { type: "h2", id: "contraintes", text: { fr: "Contraintes que je me fixe", en: "Self-imposed constraints" } },
      { type: "list", items: [
        "Zero client JavaScript by default",
        "No image above the fold",
        "Max reading width: 680 pixels",
        "It all fits in one average article"
      ]},
      { type: "h2", id: "typographie", text: { fr: "La typographie fait le travail", en: "Typography does the heavy lifting" } },
      { type: "p", text: "When you strip away garish colors, loading spinners, testimonial carousels — typography remains. And it's enough. A good serif/sans pair, a disciplined modular scale, generous leading, and eighty percent of the work is done." },
      { type: "code", lang: "css", code: "/* The scale I use everywhere */\n:root {\n  --step--2: clamp(.75rem, .72rem + .13vw, .83rem);\n  --step--1: clamp(.875rem, .83rem + .21vw, 1rem);\n  --step-0:  clamp(1rem, .93rem + .35vw, 1.25rem);\n  --step-1:  clamp(1.25rem, 1.14rem + .57vw, 1.6rem);\n  --step-2:  clamp(1.56rem, 1.38rem + .9vw, 2.1rem);\n  --step-3:  clamp(1.95rem, 1.68rem + 1.4vw, 2.75rem);\n}" },
      { type: "h2", id: "accessibilite", text: { fr: "Accessibilité n'est pas négociable", en: "Accessibility isn't negotiable" } },
      { type: "p", text: "An inaccessible portfolio says something about you before you've said a word. Lighthouse 100 isn't a trophy — it's a threshold. Then the real work starts: keyboard nav, contrast, landmarks, <code>prefers-reduced-motion</code>." },
      { type: "p", text: "V6 will come. Sooner than I think." },
    ]
  },
  ARTICLE_3: {
    fr: [
      { type: "p", text: "J'ai passé la dernière année à remplacer des bibliothèques d'animation par trois lignes de CSS. Voici ce qui marche." },
      { type: "h2", id: "idee", text: { fr: "L'idée", en: "The idea" } },
      { type: "p", text: "L'API <code>View Transitions</code> te laisse animer entre deux états du DOM comme si tu passais d'une diapo à l'autre. Le navigateur prend un snapshot du <em>avant</em>, applique tes changements, prend un snapshot du <em>après</em>, et morph les deux." },
      { type: "code", lang: "css", code: "::view-transition-old(root),\n::view-transition-new(root) {\n  animation-duration: .3s;\n  animation-timing-function: cubic-bezier(.4,0,.2,1);\n}" },
      { type: "h2", id: "pratique", text: { fr: "En pratique", en: "In practice" } },
      { type: "p", text: "Tu <code>startViewTransition(() => { /* tes mutations */ })</code>, et tu laisses le navigateur faire. Pas de refs, pas de <code>AnimatePresence</code>, pas de <code>key</code> sur des composants fantômes." },
      { type: "h2", id: "pieges", text: { fr: "Pièges", en: "Gotchas" } },
      { type: "list", items: [
        "Safari n'est pas encore de la partie (avril 2026)",
        "Les animations coûtent du repaint — un hero pleine page, oui ; un tableau de 2000 lignes, non",
        "<code>view-transition-name</code> doit être unique sur la page au moment de la transition",
      ]},
      { type: "p", text: "C'est l'une des rares fois où la plateforme web a livré exactement ce qu'on espérait. Savourons." },
    ],
    en: [
      { type: "p", text: "I spent the last year swapping animation libraries for three lines of CSS. Here's what holds up." },
      { type: "h2", id: "idee", text: { fr: "L'idée", en: "The idea" } },
      { type: "p", text: "The <code>View Transitions</code> API lets you animate between two DOM states like slides. The browser snapshots <em>before</em>, applies your change, snapshots <em>after</em>, morphs between them." },
      { type: "code", lang: "css", code: "::view-transition-old(root),\n::view-transition-new(root) {\n  animation-duration: .3s;\n  animation-timing-function: cubic-bezier(.4,0,.2,1);\n}" },
      { type: "h2", id: "pratique", text: { fr: "En pratique", en: "In practice" } },
      { type: "p", text: "You <code>startViewTransition(() => { /* your mutations */ })</code> and let the browser handle it. No refs, no <code>AnimatePresence</code>, no <code>key</code> on ghost components." },
      { type: "h2", id: "pieges", text: { fr: "Pièges", en: "Gotchas" } },
      { type: "list", items: [
        "Safari isn't in yet (April 2026)",
        "Animations cost repaint — a full-page hero, fine; a 2000-row table, not",
        "<code>view-transition-name</code> must be unique on the page during transition",
      ]},
      { type: "p", text: "One of the rare times the web platform delivered exactly what we asked for. Let's savor it." },
    ]
  },
  ARTICLE_4: {
    fr: [
      { type: "p", text: "<code>packages.edwinfom.dev</code> est passé d'un single-repo à un monorepo <code>pnpm</code> + <code>changesets</code> en un week-end. Voilà pourquoi." },
      { type: "h2", id: "pourquoi", text: { fr: "Pourquoi", en: "Why" } },
      { type: "p", text: "Trois packages, trois <code>CHANGELOG.md</code>, trois pipelines CI, et un humain (moi) qui oubliait toujours de bump la version du troisième. Le monorepo n'a pas été un choix esthétique — c'était une dette opérationnelle." },
      { type: "h2", id: "structure", text: { fr: "Structure", en: "Structure" } },
      { type: "code", lang: "bash", code: "packages/\n  tinykit/\n  type-scale/\n  md-helpers/\napps/\n  docs/\n.changeset/\npnpm-workspace.yaml" },
      { type: "h2", id: "publication", text: { fr: "Publication automatisée", en: "Automated publishing" } },
      { type: "p", text: "Un workflow GitHub Actions, un secret <code>NPM_TOKEN</code>, et <code>changesets/action</code> fait le reste. Les PR qui touchent un package demandent un <code>.changeset</code>. Le bot ouvre une PR \"Version Packages\" qui bumpe, met à jour les changelogs, et publie quand on la merge." },
      { type: "p", text: "Mon cerveau peut maintenant se concentrer sur le code, pas sur les rituels." },
    ],
    en: [
      { type: "p", text: "<code>packages.edwinfom.dev</code> went from single-repo to <code>pnpm</code> + <code>changesets</code> monorepo in one weekend. Here's why." },
      { type: "h2", id: "pourquoi", text: { fr: "Pourquoi", en: "Why" } },
      { type: "p", text: "Three packages, three <code>CHANGELOG.md</code>s, three CI pipelines, and one human (me) who kept forgetting to bump the third. The monorepo wasn't an aesthetic choice — it was operational debt." },
      { type: "h2", id: "structure", text: { fr: "Structure", en: "Structure" } },
      { type: "code", lang: "bash", code: "packages/\n  tinykit/\n  type-scale/\n  md-helpers/\napps/\n  docs/\n.changeset/\npnpm-workspace.yaml" },
      { type: "h2", id: "publication", text: { fr: "Publication automatisée", en: "Automated publishing" } },
      { type: "p", text: "One GitHub Actions workflow, one <code>NPM_TOKEN</code> secret, and <code>changesets/action</code> does the rest. PRs touching a package require a <code>.changeset</code>. The bot opens a \"Version Packages\" PR that bumps, updates changelogs, and publishes on merge." },
      { type: "p", text: "My brain can now focus on code, not rituals." },
    ]
  },
  ARTICLE_5: {
    fr: [
      { type: "p", text: "Sept lignes. Trois jours de review. Et ce petit bonheur stupide quand le mainteneur tape <em>merged</em>." },
      { type: "h2", id: "bug", text: { fr: "Le bug", en: "The bug" } },
      { type: "p", text: "Dans un lecteur markdown que j'utilise tous les jours, les liens internes ne scrollaient pas vers l'ancre cible quand le document contenait un <code>data-prefix</code>. Un cas ultra-spécifique — mais le mien." },
      { type: "h2", id: "fix", text: { fr: "La correction", en: "The fix" } },
      { type: "code", lang: "ts", code: "- const anchor = doc.querySelector(`#${id}`);\n+ const anchor = doc.querySelector(\n+   `#${id}, [data-anchor-id=\"${id}\"]`\n+ );" },
      { type: "h2", id: "lecon", text: { fr: "Ce que j'ai appris", en: "What I learned" } },
      { type: "p", text: "Un <code>CONTRIBUTING.md</code> bien écrit vaut quinze aller-retours dans une PR. Un test qui reproduit le bug avant le fix désamorce 80% des objections. Et la review n'est pas un combat — c'est un don de temps que quelqu'un te fait." },
    ],
    en: [
      { type: "p", text: "Seven lines. Three days of review. And that stupid little happiness when the maintainer types <em>merged</em>." },
      { type: "h2", id: "bug", text: { fr: "Le bug", en: "The bug" } },
      { type: "p", text: "In a markdown reader I use daily, internal links failed to scroll to the target anchor when the doc had a <code>data-prefix</code>. Ultra-specific edge case — but mine." },
      { type: "h2", id: "fix", text: { fr: "La correction", en: "The fix" } },
      { type: "code", lang: "ts", code: "- const anchor = doc.querySelector(`#${id}`);\n+ const anchor = doc.querySelector(\n+   `#${id}, [data-anchor-id=\"${id}\"]`\n+ );" },
      { type: "h2", id: "lecon", text: { fr: "Ce que j'ai appris", en: "What I learned" } },
      { type: "p", text: "A well-written <code>CONTRIBUTING.md</code> saves fifteen round-trips in a PR. A test that reproduces the bug before the fix defuses 80% of objections. And review isn't a fight — it's someone giving you their time." },
    ]
  },
  ARTICLE_6: {
    fr: [
      { type: "p", text: "Trois polices, une échelle modulaire, et la règle que je brise tout le temps." },
      { type: "h2", id: "pairing", text: { fr: "Le pairing", en: "The pairing" } },
      { type: "p", text: "Un serif pour le corps, un sans pour l'interface, un mono pour le code. <em>Newsreader</em> pour les longs textes, <em>Inter</em> pour la navigation, <em>JetBrains Mono</em> pour ce qui mérite une largeur fixe. C'est un trio qu'on retrouve partout — il y a une raison : il marche." },
      { type: "h2", id: "echelle", text: { fr: "L'échelle", en: "The scale" } },
      { type: "p", text: "J'utilise une échelle modulaire en ratio 1.25 (majeure tierce). Six niveaux suffisent : <code>xs, sm, base, lg, xl, 2xl</code>. Au-delà, c'est un hero — donc un choix éditorial, pas une valeur du système." },
      { type: "h2", id: "rythme", text: { fr: "Rythme vertical", en: "Vertical rhythm" } },
      { type: "p", text: "La règle que je brise tout le temps : garder les hauteurs de ligne comme des multiples d'une base (4 ou 8 pixels). Je commence chaque projet avec cette discipline, et je craque au premier heading qui mérite d'être serré." },
    ],
    en: [
      { type: "p", text: "Three typefaces, one modular scale, and the rule I keep breaking." },
      { type: "h2", id: "pairing", text: { fr: "Le pairing", en: "The pairing" } },
      { type: "p", text: "A serif for body, a sans for UI, a mono for code. <em>Newsreader</em> for long reads, <em>Inter</em> for navigation, <em>JetBrains Mono</em> for anything that earns monospace. It's a trio you see everywhere — there's a reason: it works." },
      { type: "h2", id: "echelle", text: { fr: "L'échelle", en: "The scale" } },
      { type: "p", text: "I use a modular scale at ratio 1.25 (major third). Six levels are enough: <code>xs, sm, base, lg, xl, 2xl</code>. Beyond that, it's a hero — an editorial choice, not a system value." },
      { type: "h2", id: "rythme", text: { fr: "Rythme vertical", en: "Vertical rhythm" } },
      { type: "p", text: "The rule I always break: keep line heights as multiples of a base (4 or 8 px). I start each project with that discipline, and I cave on the first heading that deserves to be tight." },
    ]
  }
};

Object.assign(window, { I18N, ARTICLES, PROJECTS, BODIES });
